name = "DocsEcon"
uuid = "bf8c052e-de86-11ea-0131-39a20d3bc8f9"
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
ModelBaseEcon = "1d16192e-b65e-11ea-11ed-0789cee22d2f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StateSpaceEcon = "e4c825b0-b65c-11ea-0b5a-6176b64e7b7f"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimeSeriesEcon = "8b6756d2-c55c-11ea-2998-5f67ea17da60"

[compat]
DiffResults = "1.0"
Distributions = "0.23"
Documenter = "0.25"
DocumenterTools = "0.1"
ForwardDiff = "0.10"
ModelBaseEcon = "0.2, 0.3"
Plots = "1.4"
StateSpaceEcon = "0.1, 0.2"
Suppressor = "0.2"
TimeSeriesEcon = "0.2.1"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
